server:
  port: 8000

spring:
  application:
    name: cloud.miles4j.eureka.server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    enable‐self‐preservation: false
    eviction‐interval‐timer‐in‐ms: 60000